---

base_name: 'some-basename'
hosted_zone_id: 'XXXXXXXXXXXXXXXXXXXXX'
hosted_zone_name: 'some-domain.com'

application_prefix: 'pluto-dev'
certificate_arn: 'arn:aws:acm:<region>:<account>:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
hub_container_image_repository_arn: 'arn:aws:ecr:<region>:<account>:repository/<repo_name>'
hub_container_image_tag: 'latest'
single_user_container_image_repository_arn: 'arn:aws:ecr:<region>:<account>:repository/<repo_name>'
single_user_container_image_tag: 'latest'

cognito_user_pool_id: '<region>_<hash>'
oauth_login_service_name: 'AWS Cognito'
oauth_login_username_key: 'preferred_username'
oauth_scope: ['openid', 'profile']

num_azs: 2
num_containers: 1

efs_policy: 'DESTROY'
temp_password: 'A-secret-1'
