name: Test AWS CDK

# Controls when the action will run. 
on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ main ]

jobs:
  aws_cdk:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install npm
        uses: actions/setup-node@v3

      - name: Install AWS CDK
        shell: bash
        run: npm install -g aws-cdk

      - name: Install Requirements
        shell: bash
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt

      - name: Check Requirements
        shell: bash
        run: python3 -m pip freeze | grep -i cognito

      - name: Run tests
        shell: bash
        run: |
            cp example_config.yaml config.yaml
            cp hub_docker/example_allowed_users hub_docker/allowed_users
            pytest